### ISSUE TITLE
Crash when trying to open editor

### ISSUE THREAD

**Issue by Kuli222** [PixelDoted/PixelsCharacterModels#11]
Pixel's Character Models - Fabric

**Describe the bug**
When pressing "R" to open editor det game crashes

**Expected behavior**
The editor would open

**Additional context**
[crash-2023-01-02_14.54.22-client.txt](https://github.com/PixelDoted/PixelsCharacterModels/files/10331980/crash-2023-01-02_14.54.22-client.txt)

**Comment by PixelDoted** [comment]
This should be fixed in [V2.0.3](https://modrinth.com/mod/pixels-character-models/version/2.0.3)
