### ISSUE TITLE
Versions on New CurseForge App Are for Fabric, Causes Error

### ISSUE THREAD

**Issue by ZaCloud** [PixelDoted/PixelsCharacterModels#2]
Yo. Sorry if this isn't how I should report this, but... I got the new CurseForge app on my computer (Windows 8.1), and using their built-in content browser, I found your mod. I added the latest one to my personal modpack, but it clearly is called "pixelscharactermodels-4B-Fabric.jar." And accordingly when I try to run it, Minecraft gave me the error in the screenshot:

![you got fabric in my forge](https://user-images.githubusercontent.com/5414712/128861234-3876e7f8-65e8-47c3-9ae8-5be676000ee0.PNG)

I don't know why Forge approved a non-Forge file (and it's not doing a good job telling me of any version conflicts, not very user-friendly for a n00b like me). I COULD just be doing something wrong because I'm totally new to this stuff...

But yeah, just wanted to let you know that somehow there's fabric in the forge. ^^;;
Just in case you accidentally put the wrong versions in there or something, so the Forge version can be made available there instead maybe.

(If it's not just me derping up or something aaaaafahdfkahlfj...)

**Comment by PixelDoted** [comment]
Pixel's Character Models - Fabric 3B-4B
was not labeled as Fabric this issue has been fixed

Thanks for the report
