### ISSUE TITLE
Crash when loading a HD skin

### ISSUE THREAD

**Issue by Cinnamon-Addict** [PixelDoted/PixelsCharacterModels#3]
Pixel's Character Models - Fabric

The bug causes an instant crash upon loading an added preset that is a HD skin, creating a preset in-game doesn't cause this crash

The HD skin would load without the forced crash

If crash reports are acceptable https://bytebin.lucko.me/3Te0cWOonw

Windows 10

This crash will happen no matter what, even following the wiki

**Comment by PixelDoted** [comment]
Pixel's Character Models - Fabric

Can I see the preset config 
(.minecraft > PCM > Presets > [Preset name])

**Comment by Cinnamon-Addict** [comment]
> Pixel's Character Models - Fabric
> 
> Can I see the preset config (.minecraft > PCM > Presets > [Preset name])

sure, I had it named Chara, the file type was .png

**Comment by PixelDoted** [comment]
I mean't the contents of the file, not the name and extension
(also the file extension should be ".json" not ".png")

**Comment by Cinnamon-Addict** [comment]
Oh sorry, ill do it in the morning

**Comment by PixelDoted** [comment]
Hello,
if you're still having this issue please leave a comment,
otherwise close this issue

**Comment by PixelDoted** [comment]
Closed due to inactivity
