### ISSUE TITLE
Unable to load or remove presets, crash when selecting editor

### ISSUE THREAD

**Issue by marzelowe** [PixelDoted/PixelsCharacterModels#5]
I created a new preset and selected it, but it prints "failed to load preset" to the chat. Attempting to remove presets results in a similar error.
Upon attempting to select the Editor the game crashes.

Log + crash:

[latest.log](https://github.com/PixelDoted/PixelsCharacterModels/files/8905182/latest.log)

[crash-2022-06-14_21.47.13-client.txt](https://github.com/PixelDoted/PixelsCharacterModels/files/8905180/crash-2022-06-14_21.47.13-client.txt)

**Comment by PixelDoted** [comment]
Does a "Presets" folder exist in .minecraft/PCM?
if not create it and try creating a preset again

**Comment by marzelowe** [comment]
.minecraft/PCM/Presets/ exists. Creating a preset successfully creates the preset .json file.
Here's the json as a text file:
[test.txt](https://github.com/PixelDoted/PixelsCharacterModels/files/8924515/test.txt)
.

**Comment by PixelDoted** [comment]
I tried using the preset file you sent
and it's working fine for me

looking back at the crash-report file
it says you're using "Windows 7 (amd64) version 6.1"
which might be the reason it's not working

**Comment by marzelowe** [comment]
I believe I have found the cause of the issue.
If you add `PixelsCharacterModels.client.sendClientMessage(PresetsPath + File.separator + path);` to PresetsSaveData.java/getPreset, this is the result:
![error](https://user-images.githubusercontent.com/87631410/174514593-f38b04f9-fcc0-4d01-94b8-0607f6a71c38.png)

I noticed the path to the file was duplicated, so I sought to examine how the file path is determined, and it seems this line in PresetsGUI.java, line 86 is responsible:
`String filePath = presets[i].getPath().replace(PixelsCharacterModels.PresetsData.PresetsPath + File.separator, "");`
It seems the purpose of this code is to get the file path for each file in the presets folder, then strip the path and file seperators from it to produce the file's name.

On my Windows machine this does not perform as expected and leaves the full path, which then has the path added to it again, causing this issue. Instead we can use .getName() and construct the full path later as necessary.

Additionally, the crash is a null pointer exception caused by using .close() on a null filestream, although this may have been desired behavior.

I will make a pull request so that you may take a look at the changes I've made to get it to work.
